config_version = "2.0"
configuration = []

[info]
name = "Default app"
description = "Default app for RobotHub"

[runtime]
application = "app.py#DefaultApplication"
workdir = "/app"

[runtime.runs_on]
type = "image"
name = "ghcr.io/luxonis/robothub-app-v2:2023.039.2206-regular"
