config_version = "2.0"
configuration = []

[info]
name = "Default app"
description = "Default app for RobotHub"

[runtime]
application = "app.py#DefaultApplication"
workdir = "/app"

[runtime.runs_on]
type = "hub-os"
version = "2023.041.1201"
