config_version = "2.0"
configuration = []

[info]
name = "Color stream"
description = "Color streaming using robothub_depthai"

[runtime]
application = "app.py#Application"
workdir = "/app"

[runtime.runs_on]
type = "hub-os"
version = "2023.041.1201"
