config_version = "2.0"

[info]
name = "YouTube Streaming App"
description = "App for YouTube streaming."

[runtime]
workdir = "/app"
application = "app.py#Application"

[runtime.runs_on]
type = "custom"
dockerfile = "Dockerfile"

[[configuration]]
key = "streaming_key"
label = "YoutTube streaming key"
field = "text"
initial_value = ""  # Paste your streaming key here
prefix = ""

[[configuration]]
key = "fps"
label = "FPS"
field = "num_range"
step = 1
min = 5
max = 30
initial_value = 30
