config_version = "2.0"

[info]
name = "Events app"
description = "This app demonstrates how to send events to RobotHub"

[runtime]
application = "app.py#Application"
workdir = "/app"

[runtime.runs_on]
type = "image"
name = "ghcr.io/luxonis/robothub-app-v2-dev:2024.107.1156-rvc2-regular"

[[configuration]]
label = "Event upload interval (seconds)"
key = "event_upload_interval"
field = "num_range"
step = 15
min = 15
max = 300
initial_value = 30

[[configuration]]
label = "FPS"
key = "fps"
field = "num_range"
step = 1
min = 1
max = 30
initial_value = 9
