config_version = "2.0"
configuration = []

[info]
name = "Person tracking"
description = "This app tracks people and reports their direction"

[runtime]
application = "app.py#Application"
workdir = "/app"

[runtime.runs_on]
type = "image"
name = "ghcr.io/luxonis/robothub-app-v2:2023.039.2206-regular"