config_version = "2.0"
configuration = []

[info]
name = "Person tracking"
description = "This app tracks people and reports their direction"

[runtime]
application = "app.py#Application"
workdir = "/app"

[runtime.runs_on]
type = "hub-os"
version = "2023.041.1201"
