config_version = "2.0"

[info]
name = "OCR reader"
description = "OCR reader"

[runtime]
application = "app.py#Application"
workdir = "/app"

[runtime.runs_on]
type = "image"
name = "ghcr.io/luxonis/robothub-app-v2:2023.275.1315-rvc2-regular"

[[configuration]]
label = "FPS"
key = "fps"
field = "num_range"
step = 1
min = 1
max = 30
initial_value = 10
