config_version = "2.0"
configuration = []

[info]
name = "Multiple streams"
description = "Enable color, depth and person detection streams at the same time"

[runtime]
application = "app.py#Application"
workdir = "/app"

[runtime.runs_on]
type = "hub-os"
version = "2023.041.1201"
